version: "1" # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 30
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    enabled: true
  identical-code:
    enabled: true
exclude_patterns:
  - "*.config.*"
  - "./__tests__"
