name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.10.3

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm lint

      - name: build
        run: pnpm build

      - uses: actions/upload-artifact@v2
        with:
          name: lib
          path: lib

  test:
    name: test on node ${{ matrix.node }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.10.3

      - uses: actions/download-artifact@v2
        with:
          name: lib
          path: lib

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: build tests
        run: pnpm tsc -p __tests__/

      - name: test
        if: ${{ matrix.node != '14.x' }}
        run: pnpm test

      - name: test coverage
        if: ${{ matrix.node == '14.x' }}
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: pnpm test
          coverageLocations: ${{github.workspace}}/coverage/clover.xml:clover
