name: Node.js CI

on:
  push: {}
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.11
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          cache: pnpm

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm lint

      - name: build
        run: pnpm build

      - uses: actions/upload-artifact@v2
        with:
          name: lib
          path: lib

  test:
    name: test on node ${{ matrix.node }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node: [18.x, 20.x, 21.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.11
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - uses: actions/download-artifact@v2
        with:
          name: lib
          path: lib

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: test
        run: pnpm test
