name: Push to dist

on:
  push:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.6.11
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          cache: pnpm

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build:prod

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: dist
          folder: dist
          commit-message: "deploy for ${{ github.sha }}"
