name: Publish to package
on:
  release:
    types: [published]

jobs:
  typedoc:
    name: "typedoc"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.3
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: pnpm

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: typedoc
        run: pnpm typedoc

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "typedoc-output"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
